const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),{transformSync}=require('next/dist/build/swc');
const fixture={balances:{PENDING:'10000',AVAILABLE:'97000',RESERVED:'0',HELD:'0',DEBT:'0'},paid_out_satang:'0',eligibility:{next_eligible_at:'2020-01-01'},settlement_mode:'MANUAL_WITHDRAWAL',accounts:[{id:'qa-account',is_current:true,status:'VERIFIED',account_type:'BANK_ACCOUNT',bank_code:'004',masked_account:'******3210'}],withdrawals:[],advertising:[],transactions:[],snapshots:[],banners:[{id:1,title:'QA creative',status:'DRAFT'}],summary:{gross_food_satang:'100000',merchant_discount_satang:'0',platform_discount_satang:'0',commission_satang:'5000',merchant_net_satang:'97000',advertising_expense_satang:'0'},csrf_token:'synthetic-csrf'};
function nodes(node,type){if(!node||typeof node!=='object')return [];return [...(node.type===type?[node]:[]),...React.Children.toArray(node.props?.children).flatMap(n=>nodes(n,type))];}
function content(node){return React.Children.toArray(node).map(v=>typeof v==='string'?v:typeof v==='object'?content(v.props?.children):String(v)).join('');}
async function harness(overrides={},mutation=async()=>({ok:true})){
 const data={...structuredClone(fixture),...overrides},states=[data],refs=[];let index=0,ri=0;
 const hooks={...React,useEffect(){},useState(initial){const i=index++;if(!(i in states))states[i]=typeof initial==='function'?initial():initial;return[states[i],v=>{states[i]=typeof v==='function'?v(states[i]):v;}];},useRef(initial){return refs[ri++]||=( {current:initial} );}};
 const filename='frontend/components/merchant-finance.js',presentation=await import('../frontend/lib/finance-presentation.mjs');
 const {code}=transformSync(fs.readFileSync(filename,'utf8'),{filename,jsc:{parser:{syntax:'ecmascript',jsx:true},transform:{react:{runtime:'automatic'}},target:'es2022'},module:{type:'commonjs'}});
 const module={exports:{}};
 vm.runInNewContext(code,{module,exports:module.exports,require:id=>id==='react'?hooks:id==='../lib/api'?{api:async()=>data}:id.endsWith('finance-presentation.mjs')?presentation:id.endsWith('review-dialog.mjs')?{openReviewDialog(){}}:id==='./icons'?{Icon:()=>null}:id.endsWith('.css')?new Proxy({},{get:(_,k)=>k==='__esModule'?false:k}):require(id),crypto:require('node:crypto'),FormData:class{constructor(form){this.values=form.values;}[Symbol.iterator](){return this.values[Symbol.iterator]();}},setInterval,clearInterval});
 const h={render(){index=0;ri=0;return module.exports.MerchantFinance({request:(path,options)=>options?mutation(path,options):Promise.resolve(data)});},html(){return renderToStaticMarkup(h.render());},button(label){return nodes(h.render(),'button').find(b=>content(b.props.children)===label);},open(label){h.button(label).props.onClick({currentTarget:{isConnected:true}});},submit(values=[]){return nodes(h.render(),'form')[0].props.onSubmit({preventDefault(){},currentTarget:{values}});},data};return h;
}
test('merchant wallet gives available balance primary hierarchy without fabricating current GP',async()=>{const h=await harness();assert.match(h.html(),/ยอดถอนได้/);assert.match(h.html(),/฿970\.00/);assert.match(h.html(),/class="balance"/);assert.doesNotMatch(h.html(),/GP ปัจจุบัน|GP 5%/);assert.equal(h.button('ถอนเงิน').props.disabled,false);});
test('zero available disables withdrawal, server cooldown prevents opening form',async()=>{for(const values of [{balances:{...fixture.balances,AVAILABLE:'0'}},{eligibility:{next_eligible_at:'2099-01-01T00:00:00Z'}}]){const h=await harness(values);assert.equal(h.button('ถอนเงิน').props.disabled,true);h.open('ถอนเงิน');assert.equal(nodes(h.render(),'dialog').length,0);}assert.match((await harness({eligibility:{next_eligible_at:'2099-01-01T00:00:00Z'}})).html(),/ถอนเงินได้อีกครั้ง/);});
test('missing account guides withdrawal to setup; configured account is masked without decrypted name',async()=>{const missing=await harness({accounts:[]});assert.match(missing.html(),/ยังไม่ได้เพิ่มบัญชีรับเงิน/);missing.open('ถอนเงิน');assert.match(missing.html(),/id="merchant-finance-dialog-title">เพิ่มบัญชีรับเงิน/);const h=await harness();h.open('ถอนเงิน');assert.match(h.html(),/ขั้นต่ำ ฿300/);assert.match(h.html(),/\*{6}3210/);assert.match(h.html(),/ยืนยันถอน/);assert.doesNotMatch(h.html(),/9876543210|encrypted_account/);});
test('withdrawal retains exact satang, CSRF, stable idempotency, retry and double submit safety',async()=>{let finish;const calls=[];const h=await harness({},(path,options)=>{calls.push({path,options});return new Promise(r=>{finish=r;});});h.open('ถอนเงิน');const first=h.submit([['amountSatang','300.01']]);await h.submit([['amountSatang','300.01']]);assert.equal(calls.length,1);assert.equal(calls[0].path,'/api/finance/merchant/withdrawals');assert.equal(JSON.parse(calls[0].options.body).amountSatang,'30001');assert.equal(calls[0].options.headers['X-Finance-CSRF'],fixture.csrf_token);assert.ok(calls[0].options.headers['Idempotency-Key']);assert.match(h.html(),/กำลังดำเนินการ/);finish({ok:true});await first;assert.match(h.html(),/ดำเนินการสำเร็จ/);});
test('failed mutation displays error inside modal and keeps request idempotency key on retry',async()=>{const keys=[];const h=await harness({},async(p,o)=>{keys.push(o.headers['Idempotency-Key']);throw new Error('ยอดไม่เพียงพอ');});h.open('ถอนเงิน');await h.submit([['amountSatang','300']]);assert.match(h.html(),/role="alert"[^>]*>ยอดไม่เพียงพอ/);await h.submit([['amountSatang','300']]);assert.equal(keys[0],keys[1]);});
test('recent withdrawals show only five masked records and readable statuses',async()=>{const h=await harness({withdrawals:Array.from({length:6},(_,i)=>({id:`record-${i}`,status:'PAID',amount_satang:'30000',created_at:'2026-10-09',bank_code:'004',masked_account:'******3210'}))});const html=h.html();assert.match(html,/โอนสำเร็จ/);assert.match(html,/record-4/);assert.doesNotMatch(html,/record-5/);assert.match(html,/คำขอ record-0/);assert.match((await harness()).html(),/เมื่อถอนเงิน รายการจะปรากฏที่นี่/);});
test('debt including signed balances is displayed exactly without changing accounting authority',async()=>{for(const [amount,expected] of [['30001','฿300.01'],['-30001','-฿300.01']]){const h=await harness({balances:{...fixture.balances,DEBT:amount}});assert.ok(h.html().includes(expected));assert.match(h.html(),/ยอดค้างชำระ/);assert.match(h.html(),/รอหักจากรายได้ในอนาคต/);}});
test('advertising insufficient balance is disabled; ready banner opens explicit confirmation',async()=>{const low=await harness({balances:{...fixture.balances,AVAILABLE:'29999'}});assert.equal(low.button('ซื้อโฆษณา ฿300').props.disabled,true);assert.match(low.html(),/ยอดถอนได้ไม่เพียงพอ/);const calls=[];const h=await harness({},async(p,o)=>{calls.push([p,JSON.parse(o.body)]);});assert.equal(h.button('ซื้อโฆษณา ฿300').props.disabled,false);h.open('ซื้อโฆษณา ฿300');assert.match(h.html(),/ยืนยันหัก ฿300/);await h.submit([['bannerId','1']]);assert.deepEqual(calls,[['/api/finance/merchant/advertising',{bannerId:1,confirm:true}]]);});
test('active campaign replaces repeat purchase with status dates and existing cancel action',async()=>{const h=await harness({advertising:[{id:'campaign',status:'ACTIVE',activated_at:'2026-10-09',scheduled_end_at:'2026-11-08',served_satang:'1000',refunded_satang:'0'}]});assert.equal(h.button('ซื้อโฆษณา ฿300'),undefined);assert.match(h.html(),/กำลังแสดง/);assert.match(h.html(),/สิ้นสุด/);h.open('ยกเลิกโฆษณา');assert.match(h.html(),/ยกเลิกหลังเริ่มแสดงไม่มีการคืนอัตโนมัติ/);});
test('automatic settlement describes request creation rather than automatic bank transfer',async()=>{const calls=[];const h=await harness({settlement_mode:'AUTO_3_DAYS'},async(p,o)=>calls.push([p,JSON.parse(o.body)]));assert.match(h.html(),/สร้างคำขอทุก 3 วัน/);assert.doesNotMatch(h.html(),/โอนอัตโนมัติทุก/);h.open('รอบการจ่าย');assert.match(h.html(),/ไม่ใช่การโอนเข้าธนาคารอัตโนมัติ/);await h.submit();assert.deepEqual(calls,[['/api/finance/merchant/settlement-mode',{mode:'MANUAL_WITHDRAWAL'}]]);});
test('activity uses actual posting bucket, side and amount with textual increase/decrease',async()=>{const h=await harness({transactions:[{id:9,kind:'AD_PURCHASE',posted_at:'2026-10-09',postings:[{kind:'MERCHANT_AVAILABLE',side:'D',amount_satang:'30000'}]}]});assert.match(h.html(),/ชำระค่าโฆษณา/);assert.match(h.html(),/พร้อมถอน · ลด/);assert.match(h.html(),/−฿300\.00/);assert.match(h.html(),/รายได้ร้านก่อนคืนเงิน/);assert.doesNotMatch(h.html(),/รายได้สุทธิร้าน/);});
test('large exact amounts wrap; responsive grid, accessible native dialog and scope are isolated',async()=>{const h=await harness({balances:{...fixture.balances,AVAILABLE:'90071992547409999'}});assert.match(h.html(),/900,719,925,474,099\.99/);h.open('ถอนเงิน');assert.match(h.html(),/<dialog[^>]*aria-labelledby=/);const css=fs.readFileSync('frontend/components/merchant-finance.module.css','utf8');assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/@media\(min-width:1024px\)/);assert.match(css,/min-height:44px/);assert.match(css,/focus-visible/);const source=fs.readFileSync('frontend/components/merchant-finance.js','utf8');assert.match(source,/openReviewDialog\(dialog.current,opener\)/);assert.doesNotMatch(source,/\/api\/finance\/admin/);assert.match(fs.readFileSync('frontend/components/staff-dev-tools.js','utf8'),/NODE_ENV === 'production' \|\| !enabled\) return null/);assert.match(fs.readFileSync('frontend/app/merchant/finance/page.js','utf8'),/roles=\{\['MANAGER'\]\}/);});

test('dialog wraps Tab and Shift+Tab within its enabled controls',async()=>{const h=await harness();h.open('ถอนเงิน');const handler=nodes(h.render(),'dialog')[0].props.onKeyDown;let focused='',prevented=0;const first={focus(){focused='first';}},last={focus(){focused='last';}},currentTarget={querySelectorAll(){return[first,last];}};handler({key:'Tab',shiftKey:true,target:first,currentTarget,preventDefault(){prevented++;}});assert.equal(focused,'last');handler({key:'Tab',shiftKey:false,target:last,currentTarget,preventDefault(){prevented++;}});assert.equal(focused,'first');assert.equal(prevented,2);});
test('pending account remains visible while a verified account stays current',async()=>{const pending={id:'new',status:'PENDING_VERIFICATION',is_current:false,account_type:'BANK_ACCOUNT',bank_code:'004',masked_account:'******7890'};const h=await harness({accounts:[pending,...fixture.accounts]});assert.match(h.html(),/บัญชีใหม่รอการยืนยัน/);assert.match(h.html(),/\*{6}7890/);assert.match(h.html(),/\*{6}3210/);assert.match((await harness({accounts:[pending]})).html(),/รอการยืนยันบัญชีรับเงิน/);});
